framework:

    serializer:
        enabled: true
        enable_attributes: true
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'
        default_context:
            allow_extra_attributes: false
