networks:
    default:
        name: 'app'
        driver: 'bridge'

services:
    ###> phpmyadmin ###
    phpmyadmin:
        image: phpmyadmin:5.2.1-apache
        container_name: phpmyadmin
        restart: 'unless-stopped'
        ports:
        - '8080:80'
        environment:
        - PMA_ARBITRARY=1
    ###< phpmyadmin ###

    ###> doctrine/doctrine-bundle ###
    database:
        image: 'mysql:8.0-debian'
        restart: 'unless-stopped'
        container_name: 'z_task_db'
        volumes:
        - 'mysql:/var/lib/mysql'
        environment:
#            MYSQL_ROOT_PASSWORD: '$MYSQL_ROOT_PASSWORD' # it's better to use it in production code
            MYSQL_ROOT_PASSWORD: 'root'
    ###< doctrine/doctrine-bundle ###

    ###> APP ###
    z_app:
        build: .
        restart: 'unless-stopped'
        container_name: 'z_app'
        volumes:
        - '.:/usr/share/nginx/www/z_app'
        - './nginx.conf:/etc/nginx/sites-enabled/default:ro'
        - './php.ini:/etc/php/8.4/cli/php.ini:ro'
        - './fpm-www.conf:/etc/php/8.4/fpm/pool.d/www.conf:ro'
        - './supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro'
        #- './php8.4-fpm.service:/etc/systemd/system/php8.4-fpm.service:ro'
        depends_on:
        - 'database'
    ###< APP ###

volumes:
    mysql:
