networks:
    default:
        name: 'app'
        driver: 'bridge'

services:
    ###> doctrine/doctrine-bundle ###
    database:
        image: 'mysql:8.0-debian'
        restart: 'unless-stopped'
        container_name: 'z_task_db'
        environment:
            MYSQL_ROOT_PASSWORD: '$MYSQL_ROOT_PASSWORD'
    ###< doctrine/doctrine-bundle ###
